spellchecker: aspell

matrix:
  - name: markdown
    sources:
      - README.md
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .en.text
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          attributes:
            - title
            - alt
          ignores:
            - code
            - pre
      - pyspelling.filters.url:
    default_encoding: utf-8
