title: 🇺🇸R!dd13r💙💛
email: 12781006+rdd13r@users.noreply.github.com
description: >-
  <p> ❤️<strong>Kotlin</strong>❤️ | <i>Scala</i> | <i>Java</i> </p>
logo: /assets/img/dadar-school-medalion.png
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
repository: rdd13r/rdd13r
author: R!dd13r
url: https://rdd13r.github.io
baseurl: /rdd13r

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-asciidoc

# Google Analytics
google_analytics: G-2ZP56CL0VR
