title: 💙💛 Architect 🇺🇸
email: 12781006+rdd13r@users.noreply.github.com
description: >-
  <h3>
    Transformative Solutions Architect <br/>
    Principal Software Engineer
  </h3>

  <p>❤️ <strong>Kotlin</strong> ❤️ <i>Scala</i> ❤️ <small>Java</small> ❤️</p>
logo: /assets/img/v.png
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
repository: rdd13r/rdd13r
author: Vadim Kuhay
url: https://rdd13r.github.io
baseurl: /rdd13r

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-asciidoc

# Google Analytics
google_analytics: G-2ZP56CL0VR

