title: 💙💛 🇺🇸 Vadim Kuhay
email: 12781006+rdd13r@users.noreply.github.com
description: >-
  <h3>Principal Software Engineer</h3>

  <p>❤️ <strong>Kotlin</strong> ❤️ <i>Scala</i> ❤️ <small>Java</small> ❤️</p>
logo: /assets/img/v.png
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
